[phases.install]
# instala as dependências
command = "pip install -r requirements.txt"

[phases.start]
# aponte para o seu script correto; se seu app está em ./app.py, use só “app.py”
command = "streamlit run app.py --server.port $PORT"