[phases.install]
# instala as dependências
command = "pip install -r requirements.txt"

[phases.start]
# aponte pro seu app dentro de streamlit_ui/
command = "streamlit run streamlit_ui/app.py --server.port $PORT"